name: Bug report
description: Create a report to help improve the extension.
title: "[BUG]"
labels:
  - bug
assignees:
  - eliashaeussler
body:
  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 version
      description: What TYPO3 version are you using?
      placeholder: 'e.g. 10.4.17'
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'e.g. 7.4.27'
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension version
      description: What version of EXT:warming are you using?
      placeholder: 'e.g. 0.3.7'
    validations:
      required: true
  - type: checkboxes
    id: composer-mode
    attributes:
      label: Composer mode
      description: Are you running TYPO3 in composer mode?
      options:
        - label: I'm running TYPO3 in composer mode.
          required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 11.4'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/eliashaeussler/typo3-warming/blob/master/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
