name: Frontend assets
on:
  pull_request:
    branches:
      - 'renovate/**'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        run: yarn --cwd Resources/Private/Frontend --frozen-lockfile

      # Re-create Frontend dist files
      - name: Re-create dist files
        run: yarn --cwd Resources/Private/Frontend build

      # Update PR
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[TASK] Automatically rebuild frontend assets'
