name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    secrets:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/typo3-extension-release.yaml@c330d8c56a96a0eba94c98e8feac29aa9f1d69da # 0.5.2
    with:
      php-version: 8.2 # renovate-ignore
      packaging-excludes-file: Build/release/packaging_exclude.php
